name: iOS
on: [push]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Node
        run: |
          npm install -g react-native-cli
          npm install -g detox-cli
          npm install -g yarn
      - name: Install Detox
        run: |
          brew tap wix/brew
          brew install applesimutils
      - name: Install Yarn Dependencies
        run: yarn install
      - name: Install Pod Dependencies
        run: cd ./ios && pod install && cd ..
      - name: Detox Build
        run: detox build --configuration ios.sim.debug
      - name: Launch metro for iOS
        run: yarn start &
      - name: Detox Test
        run: detox test --configuration ios.sim.debug --cleanup